[workspace]
# Add all Cargo packages as members of this workspace
members = ["apps/ide/src-tauri"]
default-members = ["apps/ide/src-tauri"]
resolver = "2"

[profile.release]
panic = "abort"
opt-level = 3
debug = false
